services:

  currency-converter-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    environment:
      - VITE_CURRENCY_CONVERTER_API_HOST=http://currency-converter-service
      - VITE_CURRENCY_CONVERTER_API_PORT=8080
    depends_on:
      - currency-converter-service

  currency-converter-service:
    image: currency-converter-service:0.1.0-SNAPSHOT
    environment:
      - SWOP_API_KEY
      - SWOP_HOST=https://swop.cx/rest
      - REDIS_HOST=redis
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"